#!/bin/zsh
if [ -z ${GIT_LOG_FILE+x} ]; then
      echo "GIT_LOG_FILE is unset: $GIT_LOG_FILE"
      alias git="/usr/bin/git"
      git "$@"
      alias git="/opt/scripts/gitwithlog"
  else
      echo "" >> "${GIT_LOG_FILE}"
      echo "================================================================================" >> "${GIT_LOG_FILE}"
      pwd >> "${GIT_LOG_FILE}"
      echo "$(date)" >> "${GIT_LOG_FILE}"
      echo "git $@" >> "${GIT_LOG_FILE}"
      alias git="/usr/bin/git"
      echo "Branch: $(git rev-parse --abbrev-ref HEAD)" >> "${GIT_LOG_FILE}"
      echo "SHA: $(git rev-parse HEAD)" >> "${GIT_LOG_FILE}"
      git "$@"
      alias git="/opt/scripts/gitwithlog"
fi



